name: Rust

on:
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install wasm
      run: rustup target add wasm32-unknown-unknown
    - name: install trunk
      run: cargo install trunk
    - name: trunk build
      run: trunk build
